version: '3.8'

services:
  sender-service:
    build: ./app/sender
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
    networks:
      - app-network

  listener-service:
    build: ./app/listener
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
