name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Runs every time you push to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests for Sender
        run: |
          cd ./app/sender && npm install && npm test
      - name: Run unit tests for Listener
        run: |
          cd ./app/listener && npm install && npm test

  build-and-push:
    needs: test # ONLY runs if the "test" job passes!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Sender
        uses: docker/build-push-action@v5
        with:
          context: ./app/sender
          push: true
          tags: your-username/sender-app:latest

      - name: Build and push Listener
        uses: docker/build-push-action@v5
        with:
          context: ./app/listener
          push: true
          tags: your-username/listener-app:latest